customhost = "employee.cs2ei0r3niij.us-east-1.rds.amazonaws.com"
customuser = "aws_iuser"
custompass = "12345678"
customdb = "employee"
custombucket = "s3-assignment-bucket"
customregion = "us-east-1"
